### ISSUE TITLE
Linking to bcrypt creates problems (i.e. for CMake users)

### ISSUE THREAD

**Issue by pdimov** [boostorg/uuid#122]
As reported in https://github.com/boostorg/boost_install/issues/54, using UUID from a CMake project requires one to manually link to bcrypt on Windows. That's because the CMake config files define `BOOST_ALL_NO_LIB`, which disables autolinking not just to Boost libraries (which is the intent), but to bcrypt.lib as well.

In addition, since UUID is a header-only library, it has no CMake target to which code could link in order to inherit the dependency to bcrypt.

If we're intending to keep linking to bcrypt, one option here is to create a dummy compiled library, whose only purpose would be to expose a Boost::uuid target in CMake, which would then link to bcrypt.

**Comment by Lastique** [comment]
I'm not the maintainer, but linking with bcrypt is essential. The alternative is wincrypt, but it is deprecated and I don't think is universally available.

I also don't think introducing a dummy compiled library is an adequate solution, as this creates a bunch of other problems. For example, it affects packaging and downstream dependencies for no good reason.

IMHO, this should be solved entirely in CMake and headers. One option is stop defining `BOOST_ALL_NO_LIB`. Another is ignore it for linking non-Boost libraries.

**Comment by pdimov** [comment]
Relying on autolink to hide the problem doesn't seem correct; it doesn't work for GCC. But assuming we don't care about GCC, we've had the discussion of whether BOOST_ALL_NO_LIB should apply to non-Boost libraries more than once now, without any results.

I wouldn't be in support of enabling autolink for Boost libraries when using the CMake config files; this causes nothing but trouble (even if it does help to hide errors occasionally.)

**Comment by Lastique** [comment]
Yes, enabling auto-link is just a workaround, something we could consider for 1.78. The proper solution is to find a way to generate CMake config files for header-only libraries while keeping them header-only.

**Comment by Leon0402** [comment]
> he proper solution is to find a way to generate CMake config files for header-only libraries while keeping them header-only

I would love to see this, so I can use Boost::uuid and others to correctly link all targets. In case of other libraries like Boost libraries, I also need to link other boost libraries explicitly like filesystem, which is confusing. 

Should this maybe tracked in a separate issue? Perhaps in boost_install?

**Comment by jeking3** [comment]
I'm guessing someone has a workaround for this, for now - it might be useful to share that to help others in the same situation.

**Comment by pdimov** [comment]
I changed the CMake config files to only define the corresponding library-specific _NO_LIB macro instead of `BOOST_ALL_NO_LIB`, which takes care of this and similar issues on compilers that support autolinking. (https://github.com/boostorg/boost_install/commit/258f7866c1cb1e4d1b3aebd0c4db594d373c686c)

**Comment by jeking3** [comment]
@pdimov is there anything that needs to be done here as a result of that?

**Comment by pdimov** [comment]
I don't think we can do anything in practice, short of switching to a compiled library, which is unacceptable for many. So, closing.

**Comment by jeking3** [comment]
Thanks, worked hard to keep this header-only.
