### ISSUE TITLE
#pragma message doesn't show correctly when enabled BOOST_UUID_RANDOM_PROVIDER_SHOW . GCC/Clang

### ISSUE THREAD

**Issue by raidenluikang** [boostorg/uuid#141]
source code [godbolat source with boost 1.82](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGISRqkrgAyeAyYAHI%2BAEaYxCBmpAAOqAqETgwe3r7%2BgSlpjgKh4VEssfGJdpgOGUIETMQEWT5%2BAJy2mPaFDHUNBMWRMXEJtvWNzTntCmP9YYNlw2YAlLaoXsTI7BwmGgCC5gDMWDThANQWAPIXQgAqAPpycgCSACJ3AEq7ES8XALJ3yneFwAaq9sO87kIABIXADqpy4O32e0OYWQ3iwpxMBzc0VQqQIAHovF48OhCVh6nRCcRDOhUCw7kliKgAG5kuJ3SnVAhMgwEfjEFgAOgQSSS2OwSNRDHRXkx2Nx%2BOmxNJ5NpDHpjOAjDiTCIxFF4sl0pRZgOzKYwBYTFObAUCitmAg5jMUM6tFQpwA7iRaOhXUtTcjdmECHamGEIEGAOxWFEomMvDgrWicACsvD8HC0pFQnDc1mspwUaw2mCx5p4pAImhTKwA1gkNMKAGxcMytVpmGNcVpcAfp1rp/ScSRZut5zi8BQgQK1nMp0hwWAwRAoBlJOhxciUNAsLf0eLAVrSLDszbAvCYb0XJKMTjVmi0AhxWcQaKT6JhBoAT0fvDfswxC/hc0TaDyAGkPubCCBcDC0P%2Bi6kFg0ReMAbhiLQs7cLwWA2kY4jIfgxA8ngrKYDhuaYKo1ReK%2Bk5hp0k60Hg0S0iBHhYJOBDEHgLAASsVAGMAChXjed4PrhMiCCIYjsFIMnyEoaiTroXD6IYxhFpY%2BhsbOsDMGwIB4gSpAUfE3AABxmPWeZJN0OEALTTAGBwvKYljWFwManLwbJxHxWAGdGHRdBkLiahMfgaSEcylOUej5OkAjRUlqQpQwAwJcMGlVDUAi9OMngtHo%2BXdEVswlEM8R5TMaV1X02U1RIKylusmytaOHCZqQ2a5vmHCnKoVmtk5raSKcwDIMgpytMKk0QLghAkJWBxcEsvALloSyNhI6bCp2BySDGrYaOmkhmBoXDpjG3XjqQAnpoE/X%2BdOthzjWdYrCu65rAQST0buED7oecQRKwWwjWNE1TTNc0LbwmD4AaZJ6PwsmiOIikY8pKjqMh6mkN6tJJIJ3W9a9U4cBc9GA%2BGqBUMNo3jZN02zfNi0eAe27EGtG1bd9KwIJgTBYPEoVphwD1PS9k6DTOn3bXZTZcFZwrdjGJ2tgcZitlZkhWTGBwHN1BwTshCtfYuP1rr9EBIKDvPA07R4gMAXDrShmAXpg4m3ve2ZPnQr7EO%2Bn7IUBf5QVHIFgRBDhQTBjAEPBiGTqh6GYbQ2FQfhWlEbmJFkRRVFI7RyD0Vs1ZMVLuasexf5cVsua8fx5PCVaYnXgHUlPrIcnY9IuOKPjakjAYRgoDpNgNyFEBGewpnTOZwzWbZu32Y5nAuQQbkeTPPn%2BRZQWUfAbWdGRzgQK4DVBJqzULLVyQZd0d/Jd0j%2BJXll8FT09UlRyD/cKhUZhf1yqMPod9phNXii1DaqwOoKVTBmC2A1ODMxhmzeGnthRcFOEtFGq1DgC2tjtPaPlDqGzMGYdM5pdaexjBoRIUsZYgGen1eW71Zzzm%2BsuO2SB/r0xdpuXmENjIcGhqzOGs1cHVmRitIK6MB5YwUsPWQo9VKExGCTJgZNcIoJ6mgt6NM6b0VOIzTB0j2YIgOHggh3MwZ80OMsQWNthai3FpQQxbCOFUytjwshKsJAxjbDGJhp1JAm1bKeZ6LDODm04Zbd6ytbbwHto7URR4RE8zduiLSHZrre19v7SSQdeDPlDuHL8P4QIx1qaBcCkFpLJzgghJCRdMBoQwlhHC1Z86ERbnhPApEail0nDROiDFkK1xYmxDiv5m48T4gJAxfARLdwkoHKCuNB5qKUpogmuZdCm0ntpLyuk57pMXiZZUBBV6WTVhvFYqAHIZGcq5bEB8LkWB8qcJysIsLH0ChyEKF8QF%2BBvlFQBMV77oHAc/D%2BGR36vwyAisqv8KoAOyLC8qtQwFwKfmVbFpVGqNHRQg9q5YupS0plwoaUjYb5KMAiMwwoWz4MIYo/mm0gmbybJ2PBxt9Y%2BSsudHyMZRr3V4LLJJ6COCK14Tbfh6TBFmPuRQEGWTwaQ04IyyazLgAIlbOy9lSMiFKI0rs1REh1GCEOePU2uj9E8EMXS5JpiAbmMsfq04hrWWms5Y43ma0Di8tSR4sWwxJZjhlewuWHrFV8r2jQ4UkqzCSAunQjQx10x9mkFLRJ/iUl8PtgIjcuSdyatdsMVkyBxR3FZH2O4/JKK8lUBNYpeBLw9zKTskOb5KAR1zLHJC1ZR3x2adWVpqd2kZy6VnXpedMAEWAIXYZozHDjOQpMyu0ya6CGYshBuCylnITbqs116yu6lO2dJa18lbUHJUkcnQ/hNJT08lYS5%2Blrm6uXvciyIA61JAbMATerzt4KrzCfUF58wpX0hbfGFeg4rVSJRpJFqUUOYdRUUQl38EN/0qtAzF%2BLYHocIzA4qOLiUUfmN/NqZZOoINpcY6mw1YYsAUHW04Tb5qtumAQ5aBoeVuPIaQAVLYNAydk3JuTBbY2PXjXKkxSbUkqtgGqr1Gq9zauIOIqGXGeOzX48KQTBBzWKLRlalRj6cYaJfePaQzryZsdU9TWmOmLFMw7ZNbjvGzMWYcfptakhw1C1ICLKNEsfFxr8fS9TkWpPsvk2lmTimOBFsS8m7qtkPNWwjQ8tIzhJBAA%3D)

GCC shows 
#pragma message("BOOST_UUID_RANDOM_PROVIDER_NAME " BOOST_UUID_RANDOM_PROVIDER_STRINGIFY(BOOST_UUID_RANDOM_PROVIDER_NAME))

Clang shows nothing.

Only MSVC compiler shows correctly: BOOST_UUID_RANDOM_PROVIDER_NAME bcrypt

**Comment by pdimov** [comment]
This is no longer relevant because the providers have been eliminated in favor of using `std::random_device`.
