### ISSUE TITLE
[feature request] Please consider supporting UUID v6 v7 v8 as decribed in RFC 9562

### ISSUE THREAD

**Issue by liubing** [boostorg/uuid#156]
Thanks

**Comment by pdimov** [comment]
Support for RFC 9562, including generators for UUIDv6 and UUIDv7, has already been implemented on the master branch and will be in the next release.

See https://www.boost.org/doc/libs/master/libs/uuid/ for a documentation preview.

**Comment by liubing** [comment]
Thank you very much.
