### ISSUE TITLE
uuid no longer constexpr contructable

### ISSUE THREAD

**Issue by tobias-loew** [boostorg/uuid#161]
Before version 1.85 uuid was an aggreagate and could be constexpr constructed from a sequence of bytes.
With version 1.85 this is no longer possible.
(I've got user-defined literal which converts uuid string-representation at compile-time into uuids that no longer works with 1.85.)

**Comment by pdimov** [comment]
Indeed, thanks for the report. I'll see if I can fix this between the beta and the release, as it's not as easy as just adding a `constexpr` to the constructor because `std::memcpy` isn't always `constexpr`.

**Comment by tobias-loew** [comment]
Another minor regression: before `.data` returned a reference to the array. Migration would be easier having a `data()` method returning a reference or a `std::span` to the byte representation.

**Comment by pdimov** [comment]
For a contiguous container, `data()` by convention returns a pointer to the first element. It's in principle possible to return a reference to the array which will decay to a pointer but that's a bit too inventive.

Although maybe if the constructor is constexpr, data() should be, too.

**Comment by pdimov** [comment]
It's still trivially copyable and standard layout, but no longer trivial (because the default constructor doesn't leave it uninitialized) or POD.

**Comment by pdimov** [comment]
Construction should be constexpr now on develop.

**Comment by pdimov** [comment]
Has been merged to master.
