### ISSUE TITLE
boost::uuids::random_generator is not copyable in 1.67.0 beta1

### ISSUE THREAD

**Issue by danieljames** [boostorg/uuid#61]
From the mailing list:

>I just noticed a breaking change: boost::uuids::random_generator is not copyable anymore. Is that is on purpose, it should maybe be mentioned in the release notes.

**Comment by jeking3** [comment]
Thanks.

**Comment by jeking3** [comment]
https://github.com/boostorg/website/pull/320

**Comment by MarcelRaad** [comment]
Thanks to both of you!
