### ISSUE TITLE
`boost::uuids::random_generator` is not copyable anymore.

### ISSUE THREAD

**Issue by Klaim** [boostorg/uuid#71]
Before Boost v1.67, `boost::uuids::random_generator`  was set to the boost random mtwiter random engine which is copyable. 
In Boost v1.67 (thankfully and finally) it is not set to that random engine but to a new one based on the platform API. Unfortunately it is now not copyable like the previous implementation.

I'm not sure if required to not be copyable but the change can be problematic.
Would it be possible to make it moveable and copyable?

**Comment by Lastique** [comment]
Given that `random_generator` can now hold various system handles, it cannot be made copyable without introducing reference counting, which I don't think is a good idea. It can be made movable, though.

**Comment by MarcelRaad** [comment]
Making it movable would help us very much for code that has to work with old (1.65) and new Boost versions. Either having to have two implementations of that code or having to use the old implementation, both of which I'd prefer to avoid, is the reason I haven't updated to 1.67 yet.

**Comment by Lastique** [comment]
To restore the old implementation of `random_generator` you can define `BOOST_UUID_RANDOM_GENERATOR_COMPAT`.

**Comment by jeking3** [comment]
I've been trying to make it movable over the last couple days but it isn't quite working yet.
