### ISSUE TITLE
not work on ubuntu 16.04.1 LTS

### ISSUE THREAD

**Issue by bajizhh** [boostorg/uuid#79]
**::syscall(SYS_getrandom, buf, size, flags) failed on ubuntu 16.04.1 LTS**

location:
uuid/detail/random_provider_getrandom.ipp:70

throws an exception blow:
boost::exception_detail::clone_impl<boost::exception_detail::error_info_injectorboost::uuids::entropy_error >

system kernel info:
Linux app2 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Lastique** [comment]
The `getrandom` syscall only appeared in Linux kernel 3.17, so in your kernel it is not present, which causes the error. The fact that `SYS_getrandom` is defined likely means that your installed Linux headers are from a different, newer kernel. Please, check that your linux-libc-dev package version on the build system matches the kernel you're running. If it doesn't then I'd say it's a configuration problem.

Also, you can define `BOOST_UUID_RANDOM_PROVIDER_FORCE_POSIX` to disable `getrandom` backend and use /dev/urandom.

**Comment by bajizhh** [comment]
@Lastique thank you, I fixed it according to your suggestion.

**Comment by jeking3** [comment]
So before we close this, I'd like to know if you used the `BOOST_UUID_RANDOM_PROVIDER_FORCE_POSIX` workaround.  If we need to add a fix here I'd like to know.
