### ISSUE TITLE
Getting integer_log2.hpp deprecation warnings

### ISSUE THREAD

**Issue by mwpowellhtx** [boostorg/uuid#88]
> d:\dev\boost.org\boost_1_69_0\boost\pending\integer_log2.hpp(7): note: This header is deprecated. Use <boost/integer/integer_log2.hpp> instead.

This with the latest ``Boost 1.69.0``. I'm assuming this is known at least partly.

**Comment by mwpowellhtx** [comment]
No worries. I think it is, by process of elimination, anyway.

**Comment by jeking3** [comment]
I'm not able to reproduce this on the current develop.  integer_log2 is not referenced in any uuid file.  The issue is likely in another repo?

**Comment by Lastique** [comment]
This is possibly from Boost.Random and fixed by https://github.com/boostorg/random/commit/1be44d405e48a42a63bd8d2dae739560b486a55c in develop.

**Comment by mwpowellhtx** [comment]
When I add the random generator include, that's when I get the error.

> #include <boost/uuid/random_generator.hpp>

May be a dependency you're taking, however.

**Comment by mr-j0nes** [comment]
This is not a boost/uuid problem but rather a boost/random one. Here the discussion:

https://github.com/boostorg/random/issues/49

**Comment by mwpowellhtx** [comment]
@mr-j0nes We understand that, thank you. I brought it to the floor because I do not care about *Boost.Random*. My view into the issue is *Boost.Uuid*. Out here.
